name: magicnumber
version: 1.0.0
github: "juliagracedefoor/magicnumber"
license: BSD3
author: "Julia DeFoor"
maintainer: "juliagracedefoor@gmail.com"
copyright: "Julia DeFoor"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/juliagracedefoor/magicnumber#readme>

dependencies:
  - base >= 4.7 && < 5
  - numerals
  - text

library:
  source-dirs: src

executables:
  magicnumber-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - magicnumber

tests:
  magicnumber-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - magicnumber
      - hspec
      - QuickCheck
